### ISSUE TITLE
Description doesn't match enum

### ISSUE THREAD

**Issue by jack-bliss** [VestboyMyst/openbracketformat#12]
https://github.com/VestboyMyst/openbracketformat/blob/9faa74646b201499317b1bf4875c2cca7ad1a51d/tournamentSchema.json#L158

something i noticed - the enum itself contains different strings to the examples in the description

edit: just noticed this PR which partially fixes this issue
https://github.com/VestboyMyst/openbracketformat/pull/3/files

**Comment by VestboyMyst** [comment]
thanks for noticing - should be fixed
