### ISSUE TITLE
Introduce versioning.

### ISSUE THREAD

**Issue by RLHerbert** [VestboyMyst/openbracketformat#15]
It seems very likely that the standard will change over time, especially now, and it would be smart to ensure that both library maintainers and users can conform to those changes. Perhaps introduce a MetaData object/field for the schema which can include such information.

**Comment by jack-bliss** [comment]
readme even mentions the standard will change over time - versioning seems important!

**Comment by VestboyMyst** [comment]
absolutely

**Comment by VestboyMyst** [comment]
addressed with "version" field in latest commit https://github.com/VestboyMyst/openbracketformat/commit/d65519c47410e0fb0061e842dd829234ef85a030
